name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev
  workflow_dispatch:
    inputs:
      deploy-to-prod:
        description: "Deploy to GitHub Pages"
        default: false
        required: true
        type: boolean

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    name: Build
    timeout-minutes: 20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          show-progress: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build:skiptsc

      - name: Add .nojekyll file
        run: touch ./dist/.nojekyll

      - name: Add 404.html for SPA routing
        run: cp ./dist/index.html ./dist/404.html

      - name: Upload artifact
        if: github.event_name == 'push' || inputs.deploy-to-prod == true
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

  deploy:
    name: Deploy to GitHub Pages
    if: github.event_name == 'push' || inputs.deploy-to-prod == true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
